src/main/java/tec/units/indriya/unit/BaseUnit.java, src/test/java/tec/units/indriya/unit/UnitsBaseUnitsTest.java, src/test/java/tec/units/indriya/unit/UnitsDerivedProductUnitsTest.java
Uploading commit f556b8425cf4b13c4599a0e30d130ed02bbbef16 from unitsofmeasurement/uom-se
to Indriya.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unitsofmeasurement/indriya/36)
=> Porting of Javadoc correction and additional unit tests from uom-se

src/main/java/tec/units/indriya/quantity/IntegerQuantity.java, src/test/java/tec/units/indriya/quantity/IntegerQuantityTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unitsofmeasurement/indriya/37)
=> IntegerQuantity addition

src/main/java/tech/units/indriya/internal/format/UnitTokenManager.java
And resolve some PMD and Codacy issues.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unitsofmeasurement/indriya/47)
=> Remove two unused private methods from UnitTokenManager

src/main/java/tech/units/indriya/internal/DefaultSystemOfUnitsService.java
Following discussion on https://github.com/unitsofmeasurement/unit-api/issues/83
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unitsofmeasurement/indriya/54)
=> Replace raw Class argument by Class<?>.

src/main/java/tech/units/indriya/spi/AbstractSystemOfUnitsService.java, src/test/java/tech/units/indriya/spi/SystemOfUnitsServiceTest.java
https://github.com/unitsofmeasurement/unit-api/issues/85
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unitsofmeasurement/indriya/55)
=> Make getUnit(Class) argument more specific.

src/main/java/tech/units/indriya/AbstractUnit.java, src/test/java/tech/units/indriya/function/CompositionEquivalenceTest.java
contributing to https://github.com/unitsofmeasurement/indriya/issues/3
also added a TODO to better describe, how to implement the `Simplifier`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unitsofmeasurement/indriya/63)
=> 3: CompositionEquivalenceTest: re-enable tests, that do already work

src/main/java/tech/units/indriya/AbstractConverter.java, src/main/java/tech/units/indriya/AbstractUnit.java, src/main/java/tech/units/indriya/function/PowersOfIntConverter.java, src/main/java/tech/units/indriya/function/RationalConverter.java, src/main/java/tech/units/indriya/internal/simplify/ArrayAdapter.java, src/main/java/tech/units/indriya/internal/simplify/BitScanner.java, src/main/java/tech/units/indriya/internal/simplify/SimplificationWorker.java, src/main/java/tech/units/indriya/internal/simplify/Simplifier.java, src/main/java/tech/units/indriya/spi/DimensionalModel.java, src/test/java/tech/units/indriya/function/CompositionEquivalenceTest.java
We have a `Simplifier` now that produces a normal-form. #3
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unitsofmeasurement/indriya/70)
=> Implementing Simplifier, also enabling all composition tests

src/main/java/tech/units/indriya/quantity/DoubleQuantity.java, src/main/java/tech/units/indriya/quantity/FloatQuantity.java, src/test/java/tech/units/indriya/quantity/DoubleQuantityTest.java, src/test/java/tech/units/indriya/quantity/FloatQuantityTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unitsofmeasurement/indriya/99)
=> 98 float quantity multiply with number

src/main/java/tech/units/indriya/quantity/NumberQuantity.java, src/test/java/tech/units/indriya/quantity/NumberQuantityTest.java
Fixes #111 .
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unitsofmeasurement/indriya/112)
=> Corrected NumberQuantity.decimalValue and added some unit tests to NumberQuantity

src/main/java/tech/units/indriya/quantity/QuantityDimension.java, src/test/java/tech/units/indriya/quantity/QuantityDimensionTest.java
Also some formatting for QuantityDimension.
Improves #20.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unitsofmeasurement/indriya/113)
=> Added unit tests for QuantityDimension

src/main/java/tech/units/indriya/quantity/BigIntegerQuantity.java, src/main/java/tech/units/indriya/quantity/ByteQuantity.java, src/main/java/tech/units/indriya/quantity/DecimalQuantity.java, src/main/java/tech/units/indriya/quantity/DoubleQuantity.java, src/main/java/tech/units/indriya/quantity/FloatQuantity.java, src/main/java/tech/units/indriya/quantity/IntegerQuantity.java, src/main/java/tech/units/indriya/quantity/JavaNumberQuantity.java, src/main/java/tech/units/indriya/quantity/LongQuantity.java, src/main/java/tech/units/indriya/quantity/NumberQuantity.java, src/main/java/tech/units/indriya/quantity/ShortQuantity.java, src/test/java/tech/units/indriya/quantity/BigIntegerQuantityTest.java, src/test/java/tech/units/indriya/quantity/ByteQuantityTest.java, src/test/java/tech/units/indriya/quantity/DecimalQuantityTest.java, src/test/java/tech/units/indriya/quantity/DoubleQuantityTest.java, src/test/java/tech/units/indriya/quantity/FloatQuantityTest.java, src/test/java/tech/units/indriya/quantity/IntegerQuantityTest.java, src/test/java/tech/units/indriya/quantity/LongQuantityTest.java, src/test/java/tech/units/indriya/quantity/NumberQuantityTest.java, src/test/java/tech/units/indriya/quantity/ShortQuantityTest.java
Should solve issue #67.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unitsofmeasurement/indriya/118)
=> Automatic widening in the arithmetic methods for Java Number quantities

src/main/java/tech/units/indriya/AbstractUnit.java, src/main/java/tech/units/indriya/format/SimpleUnitFormat.java, src/main/java/tech/units/indriya/unit/ProductUnit.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unitsofmeasurement/indriya/129)
=> #124: fix handling of powered units (creation and simple formatting)

src/main/java/tech/units/indriya/quantity/BigIntegerQuantity.java, src/main/java/tech/units/indriya/quantity/ByteQuantity.java, src/main/java/tech/units/indriya/quantity/DecimalQuantity.java, src/main/java/tech/units/indriya/quantity/DoubleQuantity.java, src/main/java/tech/units/indriya/quantity/FloatQuantity.java, src/main/java/tech/units/indriya/quantity/IntegerQuantity.java, src/main/java/tech/units/indriya/quantity/JavaNumberQuantity.java, src/main/java/tech/units/indriya/quantity/LongQuantity.java, src/main/java/tech/units/indriya/quantity/ShortQuantity.java, src/test/java/tech/units/indriya/internal/function/QuantityFunctionsTemperatureTest.java, src/test/java/tech/units/indriya/quantity/BigIntegerQuantityTest.java, src/test/java/tech/units/indriya/quantity/ByteQuantityTest.java, src/test/java/tech/units/indriya/quantity/DoubleQuantityTest.java, src/test/java/tech/units/indriya/quantity/FloatQuantityTest.java, src/test/java/tech/units/indriya/quantity/IntegerQuantityTest.java, src/test/java/tech/units/indriya/quantity/LongQuantityTest.java, src/test/java/tech/units/indriya/quantity/ShortQuantityTest.java
Further reduction of code duplication.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unitsofmeasurement/indriya/130)
=> 20 improve code coverage reduce code duplication in quantity package

src/main/java/tech/units/indriya/quantity/time/TemporalQuantity.java, src/test/java/tech/units/indriya/quantity/time/TemporalQuantityTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unitsofmeasurement/indriya/136)
=> Added unit tests to TemporalQuantity

src/main/java/tech/units/indriya/quantity/time/TemporalQuantity.java, src/test/java/tech/units/indriya/quantity/time/TemporalQuantityTest.java
Solves issue #139.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unitsofmeasurement/indriya/142)
=> Corrected TemporalQuantity.isBig to return false, and added a unit test

.gitignore
Hello,
Same concept with [the corresponding one from unit-api](https://github.com/unitsofmeasurement/unit-api/pull/132) here.
TB
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unitsofmeasurement/indriya/160)
=> Added file types to be ignored for IntelliJ & Mac

pom.xml
see in #159 .
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unitsofmeasurement/indriya/161)
=> update jacoco to 0.8.2 .

src/test/java/tech/units/indriya/incubator/AbsoluteVsRelativeDraft.java
It might help the discussion on 'AbsoluteVsRelative' [1] to actually have some Java code to play around with.
Note: there are 3 TODO markers, where Indryia does things differently than Mathematica does.
[1] https://github.com/unitsofmeasurement/unit-api/issues/140
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unitsofmeasurement/indriya/164)
=> Adding the Mathematica/Wolfram examples showcasing 'Temperature Units'.

README.md
Resolves #165 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unitsofmeasurement/indriya/166)
=> 165: swapped ismaintained badges with unit-api

src/main/java/tech/units/indriya/quantity/time/TemporalQuantity.java, src/test/java/tech/units/indriya/quantity/time/TemporalQuantityTest.java
Solves #169.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unitsofmeasurement/indriya/170)
=> Correcting multiplication and division in TemporalQuantity

src/main/java/tech/units/indriya/quantity/time/TimeUnitQuantity.java, src/test/java/tech/units/indriya/quantity/time/TimeUnitQuantityTest.java
Solves issue #173.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unitsofmeasurement/indriya/174)
=> TimeUnitQuantity addition, subtraction, multiplication and division with unit tests

src/main/java/tech/units/indriya/AbstractUnit.java, src/main/java/tech/units/indriya/unit/AlternateUnit.java, src/main/java/tech/units/indriya/unit/AnnotatedUnit.java, src/main/java/tech/units/indriya/unit/BaseUnit.java, src/main/java/tech/units/indriya/unit/ProductUnit.java, src/main/java/tech/units/indriya/unit/TransformedUnit.java, src/test/java/tech/units/indriya/unit/AnnotatedUnitTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unitsofmeasurement/indriya/178)
=> 20 improve code coverage annotated unit

src/main/java/tech/units/indriya/unit/ProductUnit.java, src/test/java/tech/units/indriya/unit/ProductUnitTest.java, src/test/java/tech/units/indriya/unit/UnitsTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unitsofmeasurement/indriya/184)
=> Routed ProductUnit.pow to ProductUnit.ofPow

src/main/java/tech/units/indriya/unit/Units.java
Are the changes introduced enough to consider #168 done? Do we need something more?
There was no specific description and I took the liberty to improvise.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unitsofmeasurement/indriya/188)
=> 168 update base units docs 9th draft si redefinition

src/main/java/tech/units/indriya/quantity/JavaNumericQuantity.java
@keilw  I'm not sure if this is what we want, so, I would be interested in your feedback.
Besides the (minor) format changes, what actually changed is [here](https://github.com/unitsofmeasurement/indriya/compare/master...thodorisbais:117-widen-numeric-quantities-for-multiplication-and-division?expand=1#diff-33b15b88ea918c328f88e6791f639db2R204) and [here](https://github.com/unitsofmeasurement/indriya/compare/master...thodorisbais:117-widen-numeric-quantities-for-multiplication-and-division?expand=1#diff-33b15b88ea918c328f88e6791f639db2R212)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unitsofmeasurement/indriya/191)
=> [WIP] 117: added widening for numeric multiplication/division

src/main/java/tech/units/indriya/format/NumberDelimiterQuantityFormat.java
One question before merging this: are we sure we still need `getCompoundInstance(NumberFormat numberFormat, UnitFormat unitFormat, String delimiter)` method? It looks like it's never used.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unitsofmeasurement/indriya/195)
=> 194: added fluent inner builder, improved javadocs and markup.

README.md
PR to #196
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unitsofmeasurement/indriya/197)
=> issue#196-remove Wafle

src/main/java/tech/units/indriya/AbstractUnit.java, src/test/java/tech/units/indriya/AbstractUnitTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unitsofmeasurement/indriya/205)
=> Deleted unreachable code in AbstractUnit and added unit tests for the class.

src/main/java/tech/units/indriya/AbstractUnit.java, src/main/java/tech/units/indriya/format/MixedRadix.java, src/main/java/tech/units/indriya/function/Calculus.java, src/test/java/tech/units/indriya/NumberAssertions.java, src/test/java/tech/units/indriya/format/MixedRadixTest.java
I've not filled in all the necessary Java-doc yet, since it is unclear whether `MixedRadix` will stay, and be a replacement for all the `Compound` (`MixedUnit`, `MixedQuantity`, ...) stuff or not.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unitsofmeasurement/indriya/212)
=> 211: initial commit, adds 'MixedRadix' and a corresponding test-case

src/main/java/tech/units/indriya/format/MixedRadix.java, src/main/java/tech/units/indriya/format/MixedRadixFormat.java, src/test/java/tech/units/indriya/format/MixedRadixTest.java
Regarding #211, considering new use-cases.
I've also extended the `MixedRadixTest` to keep the collection of known use-cases complete.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unitsofmeasurement/indriya/213)
=> Refinement of 'MixedRadix'

src/main/java/tech/units/indriya/function/RationalNumber.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unitsofmeasurement/indriya/225)
=> 223: RationalNumber add java-doc and toString()

src/main/java/tech/units/indriya/AbstractQuantity.java, src/main/java/tech/units/indriya/function/Calculus.java, src/main/java/tech/units/indriya/function/MixedRadix.java, src/main/java/tech/units/indriya/function/NumberSystem.java, src/main/java/tech/units/indriya/function/RationalNumber.java, src/main/java/tech/units/indriya/internal/function/calc/Calculator.java, src/main/java/tech/units/indriya/internal/function/calc/DefaultNumberSystem.java, src/main/java/tech/units/indriya/internal/function/radix/MixedRadixSupport.java, src/main/java/tech/units/indriya/internal/function/radix/Radix.java, src/main/java/tech/units/indriya/quantity/time/TemporalQuantity.java, src/main/java/tech/units/indriya/quantity/time/TimeUnitQuantity.java, src/test/java/tech/units/indriya/function/MixedRadixTest.java, src/test/java/tech/units/indriya/quantity/DecimalComparableQuantityTest.java, src/test/java/tech/units/indriya/quantity/DoubleComparableQuantityTest.java, src/test/java/tech/units/indriya/quantity/time/TemporalQuantityTest.java, src/test/java/tech/units/indriya/quantity/time/TimeQuantitiesConcurrentTest.java, src/test/java/tech/units/indriya/quantity/time/TimeQuantitiesTest.java, src/test/java/tech/units/indriya/quantity/time/TimeUnitQuantityTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unitsofmeasurement/indriya/227)
=> Use Number instead of Long to represent values in temporal Quantities.

src/main/java/tech/units/indriya/function/Calculus.java, src/main/java/tech/units/indriya/function/MixedRadix.java, src/main/java/tech/units/indriya/function/NumberSystem.java, src/main/java/tech/units/indriya/internal/function/calc/Calculator.java, src/main/java/tech/units/indriya/internal/function/calc/DefaultNumberSystem.java, src/main/java/tech/units/indriya/internal/function/radix/MixedRadixSupport.java, src/main/java/tech/units/indriya/internal/function/radix/Radix.java, src/test/java/tech/units/indriya/NumberAssertions.java, src/test/java/tech/units/indriya/NumberAssertions_Calculus.java, src/test/java/tech/units/indriya/internal/funtion/radix/MixedRadixSupportTest.java
part of #220
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unitsofmeasurement/indriya/228)
=> Delegate arithmetic complexity for mixed-radices to the NumberSystem.

src/main/java/tech/units/indriya/function/MixedRadix.java, src/main/java/tech/units/indriya/internal/function/radix/MixedRadixSupport.java, src/main/java/tech/units/indriya/quantity/CompoundQuantity.java, src/test/java/tech/units/indriya/quantity/CompoundQuantityTest.java
#211 we now also cover the uses-cases where units are not in decreasing order of significance
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unitsofmeasurement/indriya/232)
=> Properly implement CompoundQuantity.toUnit(Unit)

src/main/java/tech/units/indriya/format/CommonFormatter.java, src/main/java/tech/units/indriya/format/SimpleQuantityFormat.java, src/main/java/tech/units/indriya/function/RationalNumber.java, src/main/java/tech/units/indriya/internal/format/RationalNumberFormat.java, src/main/java/tech/units/indriya/internal/format/RationalNumberScanner.java, src/main/java/tech/units/indriya/internal/format/SimpleNumberScanner.java, src/test/java/tech/units/indriya/format/CompoundQuantityFormatTest.java, src/test/java/tech/units/indriya/format/QuantityFormatTest.java
references #211
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unitsofmeasurement/indriya/234)
=> Extends SimpleQuantitiyFormat to parse rational number format.

pom.xml
- to specifically fix eclipse build and test issues
fixes #235
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unitsofmeasurement/indriya/236)
=> 235: add maven profile 'm2e' that activates on eclipse

src/main/java/tech/units/indriya/function/RationalNumber.java
- also restores the previous hashCode() logic
- also makes RationalNumber final
references #239
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unitsofmeasurement/indriya/240)
=> 239: equality by value for RationalNumber

src/test/java/tech/units/indriya/unit/BaseUnitTest.java
Fixes #133
r? @thodorisbais 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unitsofmeasurement/indriya/260)
=> test: add a test to check base units are stored in correct order

src/main/java/tech/units/indriya/unit/Units.java
Is this how we would like to proceed with #271 @keilw ?
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unitsofmeasurement/indriya/273)
=> 271: added unit names to sample unit constants

src/test/java/tech/units/indriya/unit/UnitsTest.java
Added some unit tests to strengthen the recent improvements of #271
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unitsofmeasurement/indriya/277)
=> 271: added unit tests for getName() method

src/main/java/tech/units/indriya/internal/function/lazy/Lazy.java, src/main/java/tech/units/indriya/unit/ProductUnit.java
also tries to improve on code readability by
* adding some comments
* consolidating some Element specific algorithms into their own utility
... ElementUtil
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unitsofmeasurement/indriya/284)
=> 282 fixes ProductUnit#hashCode to be free of side-effects and thread-safe

src/main/java/tech/units/indriya/quantity/NumberQuantity.java, src/test/java/tech/units/indriya/quantity/TemperatureTest.java
fixes #288
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unitsofmeasurement/indriya/289)
=> fixes bug with scale conversion, also polishes temperature tests

src/main/java/tech/units/indriya/AbstractQuantity.java, src/main/java/tech/units/indriya/function/AbstractConverter.java, src/main/java/tech/units/indriya/quantity/NumberQuantity.java, src/test/java/tech/units/indriya/quantity/DoubleComparableQuantityTest.java, src/test/java/tech/units/indriya/quantity/TemperatureTest.java, src/test/java/tech/units/indriya/quantity/WolframTutorialTemperatureTest.java
solves  #247
implemented according to https://github.com/unitsofmeasurement/unit-api/wiki/Arithmetic-rules-for-Difference-versus-Absolute-quantities
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unitsofmeasurement/indriya/290)
=> adds support for relative quantity multiplication

src/main/java/tech/units/indriya/AbstractQuantity.java, src/main/java/tech/units/indriya/internal/function/ScaleHelper.java, src/main/java/tech/units/indriya/quantity/NumberQuantity.java, src/test/java/tech/units/indriya/quantity/AbsoluteVsRelativeTest.java, src/test/java/tech/units/indriya/quantity/QuantitiesTest.java, src/test/java/tech/units/indriya/quantity/RelativeQuantitiesTest.java, src/test/java/tech/units/indriya/quantity/WolframTutorialTemperatureTest.java
fixes #295 
(#294 not yet)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unitsofmeasurement/indriya/296)
=> Fixes Relative Quantity Unit Conversion to keep Scale

src/main/java/tech/units/indriya/internal/function/ScaleHelper.java, src/test/java/tech/units/indriya/quantity/DoubleComparableQuantityTest.java, src/test/java/tech/units/indriya/quantity/NumberComparableQuantityTest.java, src/test/java/tech/units/indriya/quantity/RelativeQuantitiesTest.java
fixes #294
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unitsofmeasurement/indriya/297)
=> 294: fixes 'Multiplication should carry over operand Units if possible'

src/main/java/tech/units/indriya/unit/ProductUnit.java, src/test/java/tech/units/indriya/SerializationRoundTrip.java, src/test/java/tech/units/indriya/unit/ProductUnitSerializationTest.java
in ref to #309
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unitsofmeasurement/indriya/311)
=> fixes ProductUnit de-serialization

src/main/java/tech/units/indriya/function/DefaultNumberSystem.java, src/main/java/tech/units/indriya/function/MixedRadix.java, src/test/java/tech/units/indriya/function/DefaultNumberSystemTest.java
references #314
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unitsofmeasurement/indriya/315)
=> fixes flipped logic on DefaultNumberSystem.isLessThanOne(...)

src/main/java/tech/units/indriya/unit/UnitDimension.java, src/test/java/tech/units/indriya/unit/UnitDimensionForeignMultiplyTest.java
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unitsofmeasurement/indriya/340)
=> Fixes conditional infinite recursive calls in UnitDimension

src/main/java/tech/units/indriya/format/SimpleUnitFormat.java
Issue #344.
Is expected to resolve https://github.com/geotools/geotools/pull/3232.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unitsofmeasurement/indriya/345)
=> allow new instances of SimpleUnitFormat to be created

src/main/java/tech/units/indriya/format/SimpleUnitFormat.java
See #394
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unitsofmeasurement/indriya/396)
=> Add ability to remove label/alias in SimpleUnitFormat

src/main/java/tech/units/indriya/function/MixedRadix.java, src/main/java/tech/units/indriya/internal/function/radix/Radix.java, src/main/java/tech/units/indriya/spi/DimensionalModel.java, src/main/java/tech/units/indriya/unit/ProductUnit.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unitsofmeasurement/indriya/428)
=> (#424) improves wording for various linearity check exceptions

src/test/java/tech/units/indriya/function/DefaultNumberSystemTest.java
Fixing failing unit test for issue #440, sorry I messed up with that when creating the PR.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unitsofmeasurement/indriya/442)
=> #440 Fix failing unit tests
